system-config-base: Add debugedit dependency
This package is now required to build packages. If it is absent
then builds will fail with the following error:

> ERROR: Cannot find the debugedit binary required for including
> source files in debug packages.